# -*- coding: utf-8 -*-
"""First Bedrock fliter out.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1szXNWNLTif8eeddPlX3QgJh_bCbk4bVS
"""

import pandas as pd
#from google.colab import files
# Upload the Excel file
#uploaded = files.upload()

def delete_empty_cells(file_name, sheet_name, column_name, output_file_name):
    # Read the Excel file
    df = pd.read_excel(file_name, sheet_name=sheet_name)

    # Delete rows with empty cells in the specified column
    df.dropna(subset=[column_name], inplace=True)

    # Save the modified dataframe to a new Excel file
    df.to_excel(output_file_name, index=False)

    print(f"Empty cells deleted in column '{column_name}' in sheet '{sheet_name}'.")
    print(f"Modified output saved to '{output_file_name}'.")

# Example usage
file_name = 'Filtered_Wisconsin_Wells_DNR.xlsx'
sheet_name = 'Sheet1'
column_name = 'FIRST_BEDROCK_FT'
output_file_name = 'Sand and Gravel filtered DNR.xlsx'

delete_empty_cells(file_name, sheet_name, column_name, output_file_name)