# -*- coding: utf-8 -*-
"""Max Contamination.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDMI0h78DLoC_UIql1y36aa6v6eE1hQD

***For each well, if a sample was taken twice in the same year, only keep the sample date that has the maximum radium concentration value for that year.***
"""

pip install xlsxwriter

from google.colab import files
uploaded = files.upload()

"""Good starting point."""

import pandas as pd
import numpy as np
import xlsxwriter
import os

def read_excel_file(file_path, sheet_name):
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    df['Sample Date'] = pd.to_datetime(df['Sample Date'])
    return df

def wells_sampled(df):
    df['Year'] = df['Sample Date'].dt.year
    df = df.groupby(['WI_UNIQUE_', 'Year']).agg({'Measured A': ['count', 'max']}).reset_index()
    df.columns = ['WI_UNIQUE_', 'Year', 'Count', 'Measured A']

    wells_sampled_once = df[df['Count'] == 1][['WI_UNIQUE_', 'Year', 'Measured A']]
    wells_sampled_multiple = df[df['Count'] > 1][['WI_UNIQUE_', 'Year', 'Measured A']]

    return wells_sampled_once, wells_sampled_multiple

def main():
    file_path = "CO_U and CO_C Wells with Ra data DNR merged -S&G in MCOAS.xlsx"
    sheet_name = "CO_U"
    output_file_path = "Updated_Wells_Data_CO_U.xlsx"

    df = read_excel_file(file_path, sheet_name)
    print(df)

    wells_sampled_once, wells_sampled_multiple = wells_sampled(df)
    combined_wells = pd.concat([wells_sampled_once, wells_sampled_multiple])

    print(len(combined_wells))
    print(combined_wells)

    # Write the DataFrame to an Excel file
    with pd.ExcelWriter(output_file_path, engine='xlsxwriter') as writer:
        combined_wells.to_excel(writer, sheet_name="Updated_Wells", index=False)

if __name__ == "__main__":
    main()