# -*- coding: utf-8 -*-
"""Sort Ra Wells 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZbDnQT4NLrKno7NXU74-TyIN5lhCE5k0
"""

from google.colab import files
uploaded = files.upload()

from openpyxl import load_workbook
import pandas as pd

def sort_radium_file(file, sheet1, output_file):
    # Read the Excel file
    excel_file = pd.read_excel(file, sheet_name=sheet1, engine='openpyxl')

    # Sort the DataFrame by the 'WI Unique' column
    column_name = 'WI Unique'  # Replace with the correct column name
    if column_name in excel_file.columns:
        sorted_excel_file = excel_file.sort_values(column_name)

        # Save the sorted DataFrame to a new Excel file
        sorted_excel_file.to_excel(output_file, index=False)
        print(f"The sorted data has been saved to '{output_file}'.")
    else:
        print(f"Column '{column_name}' does not exist in the Excel file.")

# Example usage
file = 'Ra Contamination in Public Water Supplies Merged DNR (time fixed).xlsx'
sheet1 = 'CO_U copy'
output_file = 'sorted_output.xlsx'

sort_radium_file(file, sheet1, output_file)